#!/bin/sh
set -e

# Sed PHP environments
sed -i \
    -e "s|;*date.timezone =.*|date.timezone = ${PHP_TIMEZONE}|i" \
    -e "s|;*memory_limit =.*|memory_limit = ${PHP_MEMORY_LIMIT}|i" \
    -e "s|;*upload_max_filesize =.*|upload_max_filesize = ${PHP_MAX_UPLOAD}|i" \
    -e "s|;*max_file_uploads =.*|max_file_uploads = ${PHP_MAX_FILE_UPLOAD}|i" \
    -e "s|;*post_max_size =.*|post_max_size = ${PHP_MAX_POST}|i" \
    -e "s|;*max_execution_time =.*|max_execution_time = ${PHP_MAX_EXECUTION_TIME}|i" \
    -e "s|;*max_input_vars =.*|max_input_vars = ${PHP_MAX_INPUT_VARS}|i" \
    -e "s|;*track_errors =.*|track_errors = ${PHP_TRACK_ERRORS}|i" \
    -e "s|;*session\.save_handler =.*|session\.save_handler = ${PHP_SESS_SAVE_HANDLER}|i" \
    -e "s|;*session\.save_path =.*|session\.save_path = ${PHP_SESS_SAVE_PATH}|i" \
    -e "s|;*session\.cookie_httponly =.*|session\.cookie_httponly = ${PHP_SESS_COOKIE_HTTPONLY}|i" \
    -e "s|;*session\.gc_maxlifetime =.*|session\.gc_maxlifetime = ${PHP_SESS_GC_MAXLIFETIME}|i" \
    ${PHP_INI_DIR}/php.ini

# Sed Nginx environments
sed -i "s|{{NGINX_ROOT}}|${APP_DIR}/${WEB_ROOT}|i" /etc/nginx/conf.d/default.conf

case "$1" in
    nginx)
        # Start PHP-FPM and force to run in background
        php-fpm -D
    ;;
esac

exec "$@"